# -*- coding: utf-8 -*-
"""product review summary

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mo_axUXV6oF4C3vlQSEb6jKl1zv_4svl
"""

# -*- coding: utf-8 -*-
"""product review summrizer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uc2DTMD23TvXAekpImItTXnJvzw5lwFc
"""

!pip install transformers torch pandas
from transformers import pipeline
import pandas as pd

#from sentiment analysis
sentiment = pipeline("sentiment-analysis")

#sample product review(you can change this text later)
reviews = """ the laptop starts quickly and works smoothly for daily tasks.
The screen quality is clear and good for watcing videos.
Battery backup is average and needs charging often.
The fan makes noise when many tasks are running.
Overall, it is a good laptop for students but not for students but not for programmers."""

#split reviews into sentences
sentences = reviews.split(".")
pros=[]
cons=[]
for s in sentences:
  s=s.strip()
  if s=="":
    continue
  result =sentiment(s)[0]
  if result[ "label"]=="POSITIVE":
    pros.append(s)
  elif result["label"]=="NEGATIVE":
    cons.append(s)

#take only 2 pros and 2 cons
pros=pros[:2]
cons=cons[:2]
#create table
df=pd.DataFrame({ "Pros": pros,
                 "Cons":cons
                  })
df