# -*- coding: utf-8 -*-
"""text generation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LgmPOKEM0210HHNTX-zCIcQZfm-DHIrE
"""

# -*- coding: utf-8 -*-
"""text generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VY9jFtaRFu2mjsC2f9DW8o3d2Og1lHxj
"""

!pip install transformers torch

from transformers import pipeline
#Load text generation model(gen ai)
generator = pipeline("text-generation",model="gpt2")

#input prompt
prompt = "Artificial Intelligence in finance will"
#generate text
result= generator(prompt, max_length=50, num_return_sequences=1)

print("Ai generated text:")
print(result[0]['generated_text'])